### ISSUE TITLE
draw route in the map

### ISSUE THREAD

**Issue by liodali** [openmobilemaps/maps-core#60]
can we use osmnavigation api to draw polyline using this sdk for ios ?

**Comment by julianfairfax** [comment]
If by this you mean adding directions or navigation features, I would also like this feature. Assuming they would work, and since you mentioned OSM, http://project-osrm.org/ and https://www.graphhopper.com/ are both used by https://openstreetmap.org for their routing, are open source, and could be added to this? Since swisstopo is built on-top of this project, adding this feature would allow the swisstopo app to be used for directions and navigation, meaning it would be the only maps app needed in Switzerland. Thanks for your work on this project!

**Comment by stmitt** [comment]
Hey, @liodali we provide a line layer implementation here is explained how it can be used: https://github.com/openmobilemaps/maps-core/tree/develop/ios#line-layer.
